#!/usr/bin/env python3
"""Golden fixtures for libneopix, generated by the same Pillow pipeline the
Python UI ships. C output must match these byte-for-byte."""

import os
import random

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
FIX = os.path.join(HERE, "fixtures")
random.seed(42)


def wr(name, data):
    with open(os.path.join(FIX, name), "wb") as f:
        f.write(bytes(data))


CONV_W, CONV_H = 16, 4
rgb = [random.randrange(256) for _ in range(CONV_W * CONV_H * 3)]
wr("conv_rgb.bin", rgb)

img = Image.frombytes("RGB", (CONV_W, CONV_H), bytes(rgb))
wr("conv_bgra_expected.bin", img.convert("RGBA").tobytes("raw", "BGRA"))

out565 = bytearray()
for i in range(0, len(rgb), 3):
    v = ((rgb[i] & 0xF8) << 8) | ((rgb[i + 1] & 0xFC) << 3) | (rgb[i + 2] >> 3)
    out565 += bytes((v & 0xFF, v >> 8))
wr("conv_565_expected.bin", out565)

DW, DH = 24, 10
SW, SH = 9, 5
dst = [random.randrange(256) for _ in range(DW * DH * 3)]
src = []
for i in range(SW * SH):
    src += [random.randrange(256), random.randrange(256), random.randrange(256)]
    src.append((0, 255, 128, 7, 250)[i % 5])
wr("blit_dst.bin", dst)
wr("blit_src.bin", src)

src_img = Image.frombytes("RGBA", (SW, SH), bytes(src))
for name, (x, y) in (("blit_in", (3, 2)),
                     ("blit_neg", (-4, -2)),
                     ("blit_over", (20, 7))):
    d = Image.frombytes("RGB", (DW, DH), bytes(dst))
    d.paste(src_img, (x, y), src_img)
    wr(f"{name}_expected.bin", d.tobytes())

random.seed(777)
DW2, DH2, SW2, SH2 = 240, 175, 64, 64
dst2 = bytes(random.randrange(256) for _ in range(DW2 * DH2 * 3))
src2 = bytes(random.randrange(256) for _ in range(SW2 * SH2 * 4))
wr("big_dst.bin", dst2)
wr("big_src.bin", src2)
d2 = Image.frombytes("RGB", (DW2, DH2), dst2)
s2 = Image.frombytes("RGBA", (SW2, SH2), src2)
d2.paste(s2, (88, 55), s2)
wr("big_expected.bin", d2.tobytes())

print("fixtures written")
